// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.App.Schedule = window.App.Schedule || {};

  (function($) {
    return App.Schedule.Carousel = (function(superClass) {
      extend(Carousel, superClass);

      function Carousel() {
        this.prevItem = bind(this.prevItem, this);
        this.nextItem = bind(this.nextItem, this);
        return Carousel.__super__.constructor.apply(this, arguments);
      }

      Carousel.prototype.next = ".schedule-carousel-next";

      Carousel.prototype.prev = ".schedule-carousel-prev";

      Carousel.prototype.schedule_item = ".schedule-item";

      Carousel.prototype.title_link = ".schedule-item-title-link";

      Carousel.prototype.bind = function() {
        this.bindItem("click", this.next, this.nextItem);
        this.bindItem("click", this.prev, this.prevItem);
        return true;
      };

      Carousel.prototype.renderScheduleItem = function($schedule_item, data) {
        return true;
      };

      Carousel.prototype.getEpisode = function($schedule_item, timestamp, direction) {
        var route;
        route = "station/episode/" + direction + "/" + timestamp;
        return $.get(route, function(response) {
          return console.dir(response);
        });
      };

      Carousel.prototype.nextItem = function(event) {
        var $schedule_item, timestamp;
        $schedule_item = $(event.target).prev();
        timestamp = $schedule_item.data("timestamp");
        this.getEpisode($schedule_item, timestamp, 'next');
        return true;
      };

      Carousel.prototype.prevItem = function(event) {
        var $schedule_item, timestamp;
        $schedule_item = $(event.target).next();
        timestamp = $schedule_item.data("timestamp");
        this.getEpisode($schedule_item, timestamp, 'prev');
        return true;
      };

      return Carousel;

    })(C4.Components.Base);
  })(jQuery);

}).call(this);
