# Namespace initializations
window.C4 ?= {}
window.C4.Components ?= {}
window.C4.Utilities ?= {}
window.App ?= {}
window.App.Events ?= {}
window.App.Modules ?= {}
window.App.Player ?= {}
window.App.Station ?= {}
