// Generated by CoffeeScript 1.10.0
(function() {
  (function($) {
    return App.Player.Audio = (function() {
      Audio.prototype.swfPath = "/sites/all/themes/custom/kbooui/bower_components/jPlayer/dist/jplayer/jquery.jplayer.swf";

      function Audio(wrapper) {
        var $player, $wrapper, container, endpoint;
        this.wrapper = wrapper;
        $wrapper = $(this.wrapper);
        $player = $wrapper.find(".jp-jplayer");
        container = $wrapper.find(".jp-audio").attr("id");
        endpoint = $player.attr("data-endpoint");
        $player.jPlayer({
          cssSelectorAncestor: "#" + container,
          swfPath: this.swfPath,
          supplied: "mp3",
          preload: "none",
          wmode: "window",
          smoothPlayBar: true,
          keyEnabled: true,
          remainingDuration: true,
          ready: function() {
            return $(this).jPlayer("setMedia", {
              mp3: endpoint
            });
          },
          play: function() {
            return $(this).jPlayer("pauseOthers");
          }
        });
        true;
      }

      return Audio;

    })();
  })(jQuery);

}).call(this);
