// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  (function($) {
    App.Main = (function(superClass) {
      extend(Main, superClass);

      function Main() {
        return Main.__super__.constructor.apply(this, arguments);
      }

      Main.prototype.init = function() {
        Main.__super__.init.call(this);
        C4.Utilities.Truncate.truncate();
        C4.Utilities.Window.resize(C4.Utilities.Truncate.truncate);
        new App.Schedule.Carousel();
        return true;
      };

      return Main;

    })(C4.Components.Base);
    return $(function() {
      new App.Main();
      return true;
    });
  })(jQuery);

}).call(this);
