// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  (function($) {
    return App.Events.Tabs = (function(superClass) {
      extend(Tabs, superClass);

      function Tabs() {
        this.tabChanged = bind(this.tabChanged, this);
        return Tabs.__super__.constructor.apply(this, arguments);
      }

      Tabs.prototype.tabs = ".nav.nav-pills";

      Tabs.prototype.init = function() {
        Tabs.__super__.init.call(this);
        C4.Utilities.Truncate.truncate($(this.tabs));
        return true;
      };

      Tabs.prototype.bind = function() {
        this.bindItem("shown.bs.tab", this.tabs, this.tabChanged);
        return true;
      };

      Tabs.prototype.tabChanged = function(event) {
        var tab_pane;
        tab_pane = $(event.target).attr('href');
        C4.Utilities.Truncate.truncate($(tab_pane));
        return true;
      };

      return Tabs;

    })(C4.Components.Base);
  })(jQuery);

}).call(this);
