// Generated by CoffeeScript 1.10.0
(function() {
  var modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  (function($) {
    return App.Station.OnAir = (function() {
      function OnAir() {}

      OnAir.interval = 60;

      OnAir.stream = null;

      OnAir.$el = null;

      OnAir.watch = function() {
        var callback;
        OnAir.interval = OnAir.interval * 1000;
        OnAir.$el = $('.on-air');
        OnAir.stream = OnAir.$el.attr('data-stream');
        callback = App.Station.OnAir.timeCheck;
        C4.Utilities.Timer.repeat(callback, OnAir.interval, "timeCheck");
        return true;
      };

      OnAir.timeCheck = function() {
        var d, five, minutes, zero;
        d = new Date();
        minutes = d.getMinutes();
        zero = minutes === 0;
        five = (modulo(minutes, 5)) === 0;
        if (zero || five) {
          OnAir.refresh();
        }
        return true;
      };

      OnAir.refresh = function() {
        var route, timestamp;
        timestamp = Math.floor(Date.now() / 1000);
        route = "/api/schedule/episode/" + OnAir.stream + "/at/" + timestamp;
        $.get(route, App.Station.OnAir.renderOnAir);
        return true;
      };

      OnAir.dataItem = function(item) {
        var data_item;
        data_item = {
          "title-link": item['title']
        };
        return data_item;
      };

      OnAir.renderOnAir = function(response) {
        var data;
        if (response.length === 0) {
          return;
        }
        data = OnAir.dataItem(response[0]);
        OnAir.$el.render(data);
        return true;
      };

      return OnAir;

    })();
  })(jQuery);

}).call(this);
