<?php

/**
 * Implements hook_cron().
 */
function radio_station_cron() {
  $station = new RadioStation();
//  $episodes = $station->getRippingEpisodes(Streams::One, 5);
//  $station->scheduleRippingEpisodes($episodes);
  $station->attachNewRips();
  $station->cullArchive();
}


/**
 * Implements hook_menu().
 */
function radio_station_menu() {
  $routes = RadioStationCallbacks::buildRoutes();
  return $routes;
}


function radio_station_get_episode($stream, $direction, $timestamp) {
  $data = RadioStationCallbacks::getEpisode($stream, $direction, $timestamp);
  drupal_json_output($data);
}


function radio_station_get_day($stream, $direction, $timestamp) {
  $data = RadioStationCallbacks::getDay($stream, $direction, $timestamp);
  drupal_json_output($data);
}


function radio_station_get_week($stream, $direction, $timestamp) {
  $data = RadioStationCallbacks::getWeek($stream, $direction, $timestamp);
  drupal_json_output($data);
}


function radio_station_get_schedule($stream) {
  return RadioStationCallbacks::getSchedule($stream);
}

function radio_station_get_playlist() {
  return RadioStationCallbacks::getPlaylist();
}


function radio_station_theme() {
  return RadioStationCallbacks::getTemplates();
}
