// Generated by CoffeeScript 1.9.3
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  C4.Utilities.Timer = (function() {
    function Timer() {}

    Timer.timers = {};

    Timer.delay = function(callback, ms, unique_id) {
      Timer.clearTimer(unique_id);
      Timer.timers[unique_id] = setTimeout(callback, ms);
      return true;
    };

    Timer.repeat = function(callback, ms, unique_id) {
      Timer.clearTimer(unique_id);
      Timer.timers[unique_id] = setInterval(callback, ms);
      return true;
    };

    Timer.clearTimer = function(unique_id) {
      if (unique_id == null) {
        throw "Unique id required but not provided";
      }
      if (indexOf.call(Timer.timers, unique_id) >= 0) {
        return clearTimeout(Timer.timers[unique_id]);
      }
    };

    return Timer;

  })();

}).call(this);
