// Generated by CoffeeScript 1.10.0
(function() {
  (function($) {
    return C4.Utilities.Window = (function() {
      function Window() {}

      Window.resize = function(callback) {
        $(window).resize(function() {
          return C4.Utilities.Timer.delay(callback, 500, "c4_window");
        });
        return true;
      };

      return Window;

    })();
  })(jQuery);

}).call(this);
