// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  C4.Components.Yamm = (function(superClass) {
    extend(Yamm, superClass);

    function Yamm() {
      this.yammClick = bind(this.yammClick, this);
      return Yamm.__super__.constructor.apply(this, arguments);
    }

    Yamm.prototype.yamm = '.yamm .dropdown-menu';

    Yamm.prototype.bind = function() {
      this.addItem("click", this.yamm, this.yammClick);
      return true;
    };

    Yamm.prototype.yammClick = function(event) {
      event.stopPropagation();
      return true;
    };

    return Yamm;

  })(C4.Components.Base);

}).call(this);
