<?php

/**
 * Implements hook_theme().
 */
function radio_flickr_theme() {
  return [
    'radio_flickr_gallery' => [
      'template' => 'flickr-gallery',
      'path' => drupal_get_path('module', 'radio_flickr') . '/templates',
    ],
  ];
}


function radio_flickr_preprocess_radio_flickr_gallery(&$vars) {
  $node = menu_get_object();

  try {
    if ($node->type == 'image_gallery') {
      $image_gallery = entity_metadata_wrapper('node', $node);
    } elseif (isset($node->field_image_gallery)) {
      $entity = entity_metadata_wrapper('node', $node);
      $image_gallery = $entity->field_image_gallery[0];
    } else {
      return;
    }

    $id = $image_gallery->field_flickr_photoset->value();
  } catch (EntityMetadataWrapperException $e) {
    return;
  }

  $flickr = new RadioFlickr();
  $vars['flickr_gallery'] = $flickr->getGallery($id);
}
