<?php

/**
 * Implements hook_menu().
 */
function radio_spinitron_menu() {
  $routes = RadioSpinitron::buildRoutes();
  return $routes;
}


function radio_spinitron_get_current_playlist() {
  $data = RadioSpinitron::getCurrentPlaylist();
  drupal_json_output($data);
}


function radio_spinitron_get_playlist_day($timestamp) {
  $data = RadioSpinitron::getPlaylistDay($timestamp);
  drupal_json_output($data);
}


function radio_spinitron_get_program_playlist_day($program_nid, $timestamp) {
  $data = RadioSpinitron::getProgramPlaylistDay(
    $program_nid,
    $timestamp
  );

  drupal_json_output($data);
}


function radio_spinitron_get_program_recent_playlists($program_nid) {
  $data = RadioSpinitron::getProgramRecentPlaylists($program_nid);
  drupal_json_output($data);
}
