<?php

/**
 * Provides a plugin for the '@type' meta tag.
 */
class SchemaPlaceType extends SchemaTypeBase {

  /**
   * {@inheritdoc}
   */
  public static function labels() {
    return [
      'Place',
      '- Accommodation',
      '-- Apartment',
      '-- CampingPitch',
      '-- House',
      '--- SingleFamilyResidence',
      '-- Room',
      '--- HotelRoom',
      '--- MeetingRoom',
      '-- Suite',
      '- AdministrativeArea',
      '-- City',
      '-- Country',
      '-- SchoolDistrict',
      '-- State',
      '- CivicStructure',
      '-- Airport',
      '-- Aquarium',
      '-- Beach',
      '-- Bridge',
      '-- BusStation',
      '-- BusStop',
      '-- Campground',
      '-- Cemetery',
      '-- Crematorium',
      '-- EducationalOrganization',
      '-- EventVenue',
      '-- FireStation',
      '-- GovernmentBuilding',
      '--- CityHall',
      '--- Courthouse',
      '--- DefenceEstablishment',
      '--- Embassy',
      '--- LegislativeBuilding',
      '-- Hospital',
      '-- MovieTheater',
      '-- Museum',
      '-- MusicVenue',
      '-- Park',
      '-- ParkingFacility',
      '-- PerformingArtsTheater',
      '-- PlaceOfWorship',
      '--- BuddhistTemple',
      '--- Church',
      '---- CatholicChurch',
      '--- HinduTemple',
      '--- Mosque',
      '--- Synagogue',
      '-- Playground',
      '-- PoliceStation',
      '-- PublicToilet',
      '-- RVPark',
      '-- StadiumOrArena',
      '-- SubwayStation',
      '-- TaxiStand',
      '-- TrainStation',
      '-- Zoo',
      '- Landform',
      '-- BodyOfWater',
      '--- Canal',
      '--- LakeBodyOfWater',
      '--- OceanBodyOfWater',
      '--- Pond',
      '--- Reservoir',
      '--- RiverBodyOfWater',
      '--- SeaBodyOfWater',
      '--- Waterfall',
      '-- Continent',
      '-- Mountain',
      '-- Volcano',
      '- LandmarksOrHistoricalBuildings',
      '- LocalBusiness',
      '- Residence',
      '--- ApartmentComplex',
      '--- GatedResidenceCommunity',
      '- TouristAttraction',
      '- TouristDestination',
    ];
  }

}
