// Generated by CoffeeScript 1.9.3
(function() {
  var base, base1, base2;

  if (window.C4 == null) {
    window.C4 = {};
  }

  if ((base = window.C4).Components == null) {
    base.Components = {};
  }

  if ((base1 = window.C4).Utilities == null) {
    base1.Utilities = {};
  }

  if (window.App == null) {
    window.App = {};
  }

  if ((base2 = window.App).Modules == null) {
    base2.Modules = {};
  }

}).call(this);
