// Generated by CoffeeScript 1.10.0
(function() {
  var base, base1, base2, base3, base4, base5;

  if (window.C4 == null) {
    window.C4 = {};
  }

  if ((base = window.C4).Components == null) {
    base.Components = {};
  }

  if ((base1 = window.C4).Utilities == null) {
    base1.Utilities = {};
  }

  if (window.App == null) {
    window.App = {};
  }

  if ((base2 = window.App).Events == null) {
    base2.Events = {};
  }

  if ((base3 = window.App).Modules == null) {
    base3.Modules = {};
  }

  if ((base4 = window.App).Player == null) {
    base4.Player = {};
  }

  if ((base5 = window.App).Station == null) {
    base5.Station = {};
  }

}).call(this);
